---
- name: Update
  apt: update_cache=yes

- name: Upgrade full
  apt: upgrade=full

- name: Install dependencies to prep for slimcoind
  apt: pkg={{item}} state=installed update-cache=yes
  with_items:
    - ntp
    - git
    - build-essential
    - libssl-dev
    - libdb-dev
    - libdb++-dev 
    - libqrencode-dev
    - libboost-dev

- name: Create swap space
  command: dd if=/dev/zero of=/extraswap bs=1M count=512
  when: ansible_swaptotal_mb < 1

- name: Make swap
  command: mkswap /extraswap
  when: ansible_swaptotal_mb < 1

- name: Add to fstab
  action: lineinfile dest=/etc/fstab regexp="extraswap" line="/extraswap none swap sw 0 0" state=present

- name: Turn swap on
  command: swapon -a

- name: Set swapiness
  shell: echo 0 | sudo tee /proc/sys/vm/swappiness

- name: Checkout slimcoin
  git: repo=https://github.com/slimcoin-project/slimcoin
       dest=/tmp/slimcoin
       version=v1.4

- name: Build slimcoind
  command: chdir=/tmp/slimcoin/src make -j2 -f makefile.unix USE_UPNP=- creates=/usr/local/bin/slimcoind

- name: Move slimcoind to /usr/local/bin
  command: cp /tmp/slimcoin/src/slimcoind /usr/local/bin/slimcoind creates=/usr/local/bin/slimcoind

- name: Setup ~/.slimcoin
  shell: mkdir ~/.slimcoin creates=~/.slimcoin/slimcoin.conf

- name: setup ~/.slimcoin/slimcoin.conf
  copy: src=./slimcoin.conf dest=~/.slimcoin/slimcoin.conf mode=0600

- name: Run slimcoind
  shell: slimcoind

- name: Pause for 5 seconds
  pause: seconds=5

- name: Simulate pressing enter
  shell: echo
